name:                discordBot
version:             0.1.0.0
github:              "githubuser/discordBot"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/discordBot#readme>

dependencies:
  - base >= 4.7 && < 5
  - discord-haskell
  - text
  - containers
  - dotenv
  - random
  - regex-tdfa
  - transformers  # <-- added here for general/global deps if needed

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - random
    - regex-tdfa
    - transformers  # <-- added here

executables:
  discordBot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discordBot
    - transformers      # <-- added here

tests:
  discordBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discordBot
